In [9]:
import numpy as np
import math
from scipy.linalg import lu, lu_factor, lu_solve, cho_factor, cho_solve


a = np.array([1, 1, 0])
b = np.array([-1, 2, 5])
M = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])

#1
print(np.inner(a, b))

#2
print(np.inner(M, b))

sqr_sum = 0
for i in b:
    sqr_sum += i**2
b_norm = math.sqrt(sqr_sum)

#3
print(b_norm)

LU, p = lu_factor(M)
x = lu_solve((LU, p), b)

#4
print(x)

c, low = cho_factor(M)
result_e = cho_solve((c, low), b)

#5
print(result_e)


1
[-4  0  8]
5.477225575051661
[1.5 4.  4.5]
[1.5 4.  4.5]
